name: CI

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.16.1
      - uses: Skiley/runfile/.github/actions/setup@master
      - run: run check

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.16.1
      - uses: Skiley/runfile/.github/actions/setup@master
      - run: run test
